/**
 * This code was generated by Builder.io.
 */
import React from "react";

const ContactSection = () => {
  return (
    <section className="contact-section">
      <h2 className="contact-title">Get in touch</h2>
      <p className="contact-description">
        Our friendly team would love to hear from you.
      </p>
      <button className="contact-button">
        <span className="contact-button-text">Contact Us</span>
        <img
          loading="lazy"
          src="https://cdn.builder.io/api/v1/image/assets/TEMP/6d2f1227c52dbebf3b3145e9d6bc80f583a09dd979714d9b8c94fa93f90f1901?apiKey=9c41d9f7ad734af2a431cbd2cb8742aa&"
          className="contact-button-icon"
          alt=""
        />
      </button>
    </section>
  );
};

export default ContactSection;
