/**
 * This code was generated by Builder.io.
 */
import React from "react";

const Footer = () => {
  return (
    <footer className="footer">
      <div className="footer-content">
        <div className="footer-logo">
          <img
            loading="lazy"
            src="https://cdn.builder.io/api/v1/image/assets/TEMP/9ad52fbc120df4e593513715a76363f4b9866c7081715fa76e1453f3eb5d07bb?apiKey=9c41d9f7ad734af2a431cbd2cb8742aa&"
            className="footer-logo-icon"
            alt="PortfoliOH logo icon"
          />
          <img
            loading="lazy"
            src="https://cdn.builder.io/api/v1/image/assets/TEMP/e02d77d227fb3709d1b29edc9063b39ddd47d212986f41825383d0b5ada00cff?apiKey=9c41d9f7ad734af2a431cbd2cb8742aa&"
            className="footer-logo-text"
            alt="PortfoliOH logo text"
          />
        </div>
        <nav className="footer-nav">
          <a href="#students" className="footer-link">
            For Students
          </a>
          <a href="#educators" className="footer-link">
            For Educators
          </a>
          <a href="#business" className="footer-link">
            For Business
          </a>
          <a href="#privacy" className="footer-link">
            Privacy Policy
          </a>
          <a href="#terms" className="footer-link">
            Terms & Conditions
          </a>
        </nav>
      </div>
      <div className="footer-newsletter">
        <h3 className="footer-newsletter-title">Get Email Notifications</h3>
        <p className="footer-newsletter-description">
          Sign up to our e-mail newsletter to receive the latest news & updates.
        </p>
        <form className="footer-form">
          <label htmlFor="emailInput" className="visually-hidden">
            Input your email
          </label>
          <input
            type="email"
            id="emailInput"
            className="footer-input"
            placeholder="Input your email."
            aria-label="Input your email"
          />
          <button type="submit" className="footer-submit">
            Submit
          </button>
        </form>
      </div>
      <div className="footer-bottom">
        <p className="footer-copyright">© 2023 All Rights Reserved.</p>
        <div className="footer-social">
          <a href="#facebook" aria-label="Facebook">
            <img
              loading="lazy"
              src="https://cdn.builder.io/api/v1/image/assets/TEMP/590d6908d0b322c9125915bb651f1036b5b924c55b4aa1a8ce6084f6a1ca29fa?apiKey=9c41d9f7ad734af2a431cbd2cb8742aa&"
              className="footer-social-icon"
              alt=""
            />
          </a>
          <a href="#twitter" aria-label="Twitter">
            <img
              loading="lazy"
              src="https://cdn.builder.io/api/v1/image/assets/TEMP/23d87b5cd242b7473ce159315aed19fee9add2716670a1046c1412d7092e87ff?apiKey=9c41d9f7ad734af2a431cbd2cb8742aa&"
              className="footer-social-icon"
              alt=""
            />
          </a>
          <a href="#linkedin" aria-label="LinkedIn">
            <img
              loading="lazy"
              src="https://cdn.builder.io/api/v1/image/assets/TEMP/f3c4f9feeddc69d009906536a9647b1d773657d64c6dbcecec2e846af0042503?apiKey=9c41d9f7ad734af2a431cbd2cb8742aa&"
              className="footer-social-icon"
              alt=""
            />
          </a>
        </div>
      </div>
    </footer>
  );
};

export default Footer;
