/**
 * This code was generated by Builder.io.
 */
import React from "react";

const TestimonialSection = ({ testimonials }) => {
  return (
    <section className="testimonial-section">
      <h2 className="section-title">What our clients think about PortfoliOH</h2>
      {testimonials.map((testimonial, index) => (
        <div key={index} className="testimonial">
          <div className="testimonial-content">
            <div className="testimonial-rating">
              {[...Array(5)].map((_, i) => (
                <img
                  key={i}
                  loading="lazy"
                  src="https://cdn.builder.io/api/v1/image/assets/TEMP/d13a83d45e6b801c0872ca0c18965bc89700124e2a4561089e481d1502208851?apiKey=9c41d9f7ad734af2a431cbd2cb8742aa&"
                  className="star-icon"
                  alt=""
                />
              ))}
            </div>
            <p className="testimonial-text">{testimonial.text}</p>
          </div>
          <img
            loading="lazy"
            src={testimonial.imageSrc}
            className="testimonial-image"
            alt={testimonial.imageAlt}
          />
        </div>
      ))}
    </section>
  );
};

export default TestimonialSection;
