/**
 * This code was generated by Builder.io.
 */
import * as React from "react";

function MyComponent() {
  return (
    <>
      <img
        loading="lazy"
        src="https://cdn.builder.io/api/v1/image/assets/TEMP/4aa3bf275898e6bfb8900b589645fa2b96e029810d40a88848d63415d8a462c8?"
        className="img"
      />
      <style jsx>{`
        .img {
          aspect-ratio: 5.88;
          object-fit: auto;
          object-position: center;
          width: 100%;
          fill: #0b3550;
          max-width: 133px;
        }
      `}</style>
    </>
  );
}
